version: "3.7"

services: 
  app:
    build: 
      context: .
    env_file: 
      - .env
    ports: 
      - "${APP_PORT}:8000"
    volumes: 
      - ./app:/app
    command: >
      bash -c "/scripts/wait-for-it.sh mysql:${MYSQL_FORWARD_PORT} -t 0 
      && /scripts/startserver.sh
      && python manage.py runserver 0.0.0.0:${APP_PORT}"
    environment: 
      - DEBUG=1
    depends_on: 
      - mysql

  mysql:
    image: mysql:8
    restart: always
    env_file: 
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes: 
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/database:/var/lib/mysql
    ports: 
      - "${MYSQL_HOST_PORT}:${MYSQL_FORWARD_PORT}"
    