version: "3.7"

services: 
  app:
    build: 
      context: .
    env_file: 
      - .env
    ports: 
      - "${APP_HOST_PORT}:${APP_FOWARD_PORT}"
    volumes: 
      - ./app:/app
    command: >
      bash -c "/scripts/wait-for-it.sh mysql:${MYSQL_FORWARD_PORT} -t 0 
      && tail -f /dev/null"
    environment: 
      - DEBUG=1
    depends_on: 
      - mysql

  mysql:
    image: mariadb
    env_file: 
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes: 
      # - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/database:/var/lib/mysql
    ports: 
      - "${MYSQL_HOST_PORT}:${MYSQL_FORWARD_PORT}"
    